# Generated by Django 4.0.3 on 2022-04-21 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=1023)),
                ('content', models.TextField(max_length=4095)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('from_email', models.EmailField(blank=True, default=None, max_length=150)),
                ('subject', models.CharField(blank=True, max_length=1023)),
                ('content', models.TextField(blank=True, max_length=4095)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_challenge_app.email_template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
